language: python
python:
#  - "2.7"
  - "3.5"
sudo: false
install:
  - pip install nose
  - pip install flake8 pydocstyle
# For now install ament_package from git
  - git clone https://github.com/ament/ament_package.git
  - cd ament_package
  - python setup.py install
  - cd ..
# For now install osrf_pycommon from git
  - git clone https://github.com/osrf/osrf_pycommon.git
  - cd osrf_pycommon
  - python setup.py install
  - cd ..
# For now install ament_copyright / ament_flake8 / ament_pep257 from git
  - git clone https://github.com/ament/ament_lint.git
  - cd ament_lint/ament_copyright
  - python setup.py install
  - cd ../..
  - cd ament_lint/ament_flake8
  - python setup.py install
  - cd ../..
  - cd ament_lint/ament_pep257
  - python setup.py install
  - cd ../..
script:
  - python setup.py nosetests -s
notifications:
  email: false
